server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    com.hazelcast: TRACE
    org.redisson: DEBUG

com:
  blax:
    hz:
      enable: true
      bootstrap-address: docker.vm:5701
      cluster-name: blax
    redis:
      enable: true

# https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter
spring:
  redis:
    password: blax
    timeout: 5000
    cluster:
      nodes:
        - docker.vm:6379