version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6379
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
    network_mode: "host"

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6380
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
    network_mode: "host"

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6381
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
    network_mode: "host"

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6382
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
    network_mode: "host"

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
#      - ./conf/redis-04.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - REDIS_PASSWORD=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6383
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
    network_mode: "host"

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_PASSWORD=blax
      - REDISCLI_AUTH=blax
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=${DOCKER_HOST_IP}
      - REDIS_PORT_NUMBER=6384
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=${DOCKER_HOST_IP}:6379 ${DOCKER_HOST_IP}:6380 ${DOCKER_HOST_IP}:6381 ${DOCKER_HOST_IP}:6382 ${DOCKER_HOST_IP}:6383 ${DOCKER_HOST_IP}:6384
      - REDIS_CLUSTER_CREATOR=yes
    network_mode: "host"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
