version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
#      - ./conf/redis-00.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6379'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    network_mode: "host"
#    command: ["sh", "-c", "echo 'cluster-announce-port 6379' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    # ports:
    #   - 6379:6379

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
#      - ./conf/redis-01.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6380'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   command: ["sh", "-c", "echo 'cluster-announce-port 6380' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    network_mode: "host"
    # ports:
    #   - 6380:6380

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
#      - ./conf/redis-02.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6381'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    network_mode: "host"
#    command: ["sh", "-c", "echo 'cluster-announce-port 6381' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    # ports:
    #   - 6381:6381

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
#      - ./conf/redis-03.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6382'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    network_mode: "host"
#    command: ["sh", "-c", "echo 'cluster-announce-port 6382' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    # ports:
    #   - 6382:6382

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
#      - ./conf/redis-04.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6383'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    network_mode: "host"
#    command: ["sh", "-c", "echo 'cluster-announce-port 6383' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    # ports:
    #   - 6383:6383

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
#      - ./conf/redis-05.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=blax'
      - 'REDISCLI_AUTH=blax'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.99.100'
      - 'REDIS_PORT_NUMBER=6384'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=192.168.99.100:6379 192.168.99.100:6380 192.168.99.100:6381 192.168.99.100:6382 192.168.99.100:6383 192.168.99.100:6384'
#      - 'REDIS_NODES=redis-node-0:6379 redis-node-1:6380 redis-node-2:6381 redis-node-3:6382 redis-node-4:6383 redis-node-5:6384'
      - 'REDIS_CLUSTER_CREATOR=yes'
    network_mode: "host"
#    command: ["sh", "-c", "echo 'cluster-announce-port 6384' >> /opt/bitnami/redis/etc/redis.conf && /opt/bitnami/scripts/redis-cluster/run.sh"]
    # ports:
    #   - 6384:6384

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local    